### PR TITLE
PHP 8.4 compatibility

### PR DESCRIPTION
**Pull request by andypost**
RFC https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

### CODE REVIEW

**Comment by andypost** [comment]
Testing with official docker image `docker run --rm -v $(pwd):/mnt -w /mnt php:8.4.0alpha2-cli-alpine find . -type f -name '*.php' -exec php -l {} \;`

**Comment by mck89** [comment]
That would break the compatibility with PHP < 7 since nullable types were introduced in that version, it's not a big deal but i prefer to keep it until possibile. Maybe removing the type declaration just for this methods is enough, i will investigate it.

**Comment by mck89** [comment]
I've chosen to proceed in the way i described opening a new pull request #70, i'll close this one, thank you anyway!

**Comment by andypost** [comment]
Thank you!

**Pull request closed without merging**
